protected/models/Genjournal.php
<?php

/**
 * This is the model class for table "genjournal".
 *
 * The followings are the available columns in table 'genjournal':
 * @property integer $genjournalid
 * @property string $referenceno
 * @property string $journaldate
 * @property string $journalnote
 * @property integer $recordstatus
 *
 * The followings are the available model relations:
 * @property Journaldetail[] $journaldetails
 */
class Genjournal extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return Genjournal the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'genjournal';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('recordstatus', 'numerical', 'integerOnly'=>true),
			array('referenceno', 'length', 'max'=>50),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('genjournalid, referenceno, journaldate, journalnote, recordstatus', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'journaldetails' => array(self::HAS_MANY, 'Journaldetail', 'genjournalid'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'genjournalid' => 'ID',
			'referenceno' => 'Reference No',
			'journaldate' => 'Journal Date',
			'journalnote' => 'Journal Note',
			'postdate'=>'Post Date',
			'recordstatus' => 'Record Status',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;
		$criteria->compare('genjournalid',$this->genjournalid);
		$criteria->compare('referenceno',$this->referenceno,true);
		$criteria->compare('journaldate',$this->journaldate,true);
		$criteria->compare('postdate',$this->postdate,true);
		$criteria->compare('journalnote',$this->journalnote,true);
		$criteria->compare('recordstatus',$this->recordstatus);

		return new CActiveDataProvider(get_class($this), array(
'pagination'=>array(
        'pageSize'=> Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']),
    ),
			'criteria'=>$criteria,
		));
	}

    public function beforeSave() {
        $this->journaldate = date(Yii::app()->params['datetodb'], strtotime($this->journaldate));
        $this->postdate = date(Yii::app()->params['datetodb'], strtotime($this->postdate));
    return parent::beforeSave();
}

	public function searchwstatus()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;
		$criteria->condition='recordstatus=1';
		$criteria->compare('genjournalid',$this->genjournalid);
		$criteria->compare('referenceno',$this->referenceno,true);
		$criteria->compare('journaldate',$this->journaldate,true);
		$criteria->compare('journalnote',$this->journalnote,true);
		$criteria->compare('recordstatus',$this->recordstatus);

		return new CActiveDataProvider(get_class($this), array(
'pagination'=>array(
        'pageSize'=> Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']),
    ),
			'criteria'=>$criteria,
		));
	}

	public function searchwfstatus()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;
$criteria->condition="t.recordstatus in (select b.wfbefstat
from workflow a
inner join wfgroup b on b.workflowid = a.workflowid
inner join groupaccess c on c.groupaccessid = b.groupaccessid
inner join usergroup d on d.groupaccessid = c.groupaccessid
inner join useraccess e on e.useraccessid = d.useraccessid
where upper(a.wfname) = upper('listjournal') and upper(e.username)=upper('".Yii::app()->user->name."'))";
		$criteria->compare('genjournalid',$this->genjournalid);
		$criteria->compare('referenceno',$this->referenceno,true);
		$criteria->compare('journaldate',$this->journaldate,true);
		$criteria->compare('journalnote',$this->journalnote,true);
		$criteria->compare('recordstatus',$this->recordstatus);

		return new CActiveDataProvider(get_class($this), array(
'pagination'=>array(
        'pageSize'=> Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']),
    ),
			'criteria'=>$criteria,
		));
	}

	public function behaviors()
  {
    return array(
        // Classname => path to Class
        'ActiveRecordLogableBehavior'=>
            'application.behaviors.ActiveRecordLogableBehavior',
    );
  }
}

protected/controllers/GenjournalController.php
<?php

class GenjournalController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column3';
protected $menuname = 'genjournal';

	public function actionHelp()
	{
		$txt = '';
		if (isset($_POST['id'])) {
			$id= (int)$_POST['id'];
			switch ($id) {
				case 1 : $txt = '_help'; break;
				case 2 : $txt = '_helpmodif'; break;
				case 3 : $txt = '_helpdetail'; break;
				case 4 : $txt = '_helpdetailmodif'; break;
			}
		}
		parent::actionHelp($txt);
	}
	
	public $journaldetail;
	

	public function lookupdata()
	{
	  $this->journaldetail=new Journaldetail('search');
	  $this->journaldetail->unsetAttributes();  // clear any default values
	  if(isset($_GET['Journaldetail']))
		$this->journaldetail->attributes=$_GET['Journaldetail'];
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
	  parent::actionCreate();
	  $this->lookupdata();
	  $model=new Genjournal;
	  $model->journaldate=new CDbExpression('NOW()');
	  $model->postdate=new CDbExpression('NOW()');
	  $model->recordstatus=Wfgroup::model()->findstatusbyuser('insjournal');
	  if (Yii::app()->request->isAjaxRequest)
	  {
		  if ($model->save()) {
			echo CJSON::encode(array(
				'status'=>'success',
				'genjournalid'=>$model->genjournalid,
				'divcreate'=>$this->renderPartial('_form', array('model'=>$model,
				  'journaldetail'=>$this->journaldetail), true)
				));
			Yii::app()->end();
		  }
	  }
	}

	public function actionCreatedetail()
	{
	  $journaldetail=new Journaldetail;
	  if (Yii::app()->request->isAjaxRequest)
	  {
		  echo CJSON::encode(array(
			  'status'=>'success',
			  'divcreate'=>$this->renderPartial('_formdetail',
				array('model'=>$journaldetail), true)
			  ));
		  Yii::app()->end();
	  }
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate()
	{
	  parent::actionUpdate();
	  $this->lookupdata();
		$id=$_POST['id'];
		$model=$this->loadModel($id[0]);
		if ($model != null)
      {
        if ($this->CheckDataLock($this->menuname, $id[0]) == false)
        {
          $this->InsertLock($this->menuname, $id[0]);
            echo CJSON::encode(array(
                'status'=>'success',
				'genjournalid'=>$model->genjournalid,
				'referenceno'=>$model->referenceno,
				'journaldate'=>date(Yii::app()->params['dateviewfromdb'], strtotime($model->journaldate)),
				'journalnote'=>$model->journalnote,
				'postdate'=>date(Yii::app()->params['dateviewfromdb'], strtotime($model->postdate)),
				'recordstatus'=>$model->recordstatus,
                'div'=>$this->renderPartial('_form', array('model'=>$model,
				  'journaldetail'=>$this->journaldetail), true)
				));
            Yii::app()->end();
        }
        }
	}

	public function actionUpdatedetail()
	{
		$id=$_POST['id'];
	  $journaldetail=$this->loadModeldetail($id[0]);

		// Uncomment the following line if AJAX validation is needed

		if (Yii::app()->request->isAjaxRequest)
        {
            echo CJSON::encode(array(
                'status'=>'success',
				'journaldetailid'=>$journaldetail->journaldetailid,
				'accountid'=>$journaldetail->accountid,
				'accountcode'=>($journaldetail->account!==null)?$journaldetail->account->accountcode:"",
				'accountname'=>($journaldetail->account!==null)?$journaldetail->account->accountname:"",
				'debit'=>$journaldetail->debit,
				'credit'=>$journaldetail->credit,
				'ratevalue'=>$journaldetail->ratevalue,
				'currencyid'=>$journaldetail->currencyid,
				'currencyname'=>($journaldetail->currency!==null)?$journaldetail->currency->currencyname:"",
				'detailnote'=>$journaldetail->detailnote,
                'div'=>$this->renderPartial('_formdetail',
				  array('model'=>$journaldetail), true)
				));
            Yii::app()->end();
        }
	}

    public function actionCancelWrite()
    {
      $this->DeleteLockCloseForm($this->menuname, $_POST['Genjournal'], $_POST['Genjournal']['genjournalid']);
    }

	public function actionWrite()
	{
	  parent::actionWrite();
	  if(isset($_POST['Genjournal']))
	  {
        $messages = $this->ValidateData(
                array(
                array($_POST['Genjournal']['journaldate'],'agjemptyjournaldate','emptystring'),
                array($_POST['Genjournal']['postdate'],'agjemptypostdate','emptystring'),
                array($_POST['Genjournal']['journalnote'],'agjemptyjournalnote','emptystring'),
            )
        );
        if ($messages == '') {
		//$dataku->attributes=$_POST['Genjournal'];
		if ((int)$_POST['Genjournal']['genjournalid'] > 0)
		{
		  $model=$this->loadModel($_POST['Genjournal']['genjournalid']);
		  $model->journaldate = $_POST['Genjournal']['journaldate'];
		  $model->journalnote = $_POST['Genjournal']['journalnote'];
		  $model->postdate = $_POST['Genjournal']['postdate'];
		  $model->referenceno = $_POST['Genjournal']['referenceno'];
		}
		else
		{
		  $model = new Genjournal();
		  $model->attributes=$_POST['Genjournal'];
		}
		try
          {
            if($model->save())
            {
              $this->DeleteLock($this->menuname, $_POST['Genjournal']['genjournalid']);
              $this->GetSMessage('agjinsertsuccess');
            }
            else
            {
              $this->GetMessage($model->getErrors());
            }
          }
          catch (Exception $e)
          {
            $this->GetMessage($e->getMessage());
          }
        }
	  }
	}

	public function actionWritedetail()
	{
	  if(isset($_POST['Journaldetail']))
	  {
        $messages = $this->ValidateData(
                array(array($_POST['Journaldetail']['accountid'],'agjemptyaccount','emptystring'),
                array($_POST['Journaldetail']['debit'],'agjemptydebit','emptystring'),
                array($_POST['Journaldetail']['credit'],'agjemptycredit','emptystring'),
                array($_POST['Journaldetail']['currencyid'],'agjemptycurrency','emptystring'),
            )
        );
        if ($messages == '') {
          //$dataku->attributes=$_POST['Journaldetail'];
          if ((int)$_POST['Journaldetail']['journaldetailid'] > 0)
          {
            $model=Journaldetail::model()->findbyPK($_POST['Journaldetail']['journaldetailid']);
            $model->genjournalid = $_POST['Journaldetail']['genjournalid'];
            $model->accountid = $_POST['Journaldetail']['accountid'];
            $model->debit = $_POST['Journaldetail']['debit'];
            $model->credit = $_POST['Journaldetail']['credit'];
            $model->currencyid = $_POST['Journaldetail']['currencyid'];
            $model->ratevalue = $_POST['Journaldetail']['ratevalue'];
            $model->detailnote = $_POST['Journaldetail']['detailnote'];
          }
          else
          {
            $model = new Journaldetail();
            $model->attributes=$_POST['Journaldetail'];
          }
          try
          {
            if($model->save())
            {
              $this->GetSMessage('agjinsertsuccess');
            }
            else
            {
              $this->GetMessage($model->getErrors());
            }
          }
          catch (Exception $e)
          {
            $this->GetMessage($e->getMessage());
          }
        }
	  }
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete()
	{
	  parent::actionDelete();
		$id=$_POST['id'];
		foreach($id as $ids)
		{
		  $model=$this->loadModel($ids);
		  $model->recordstatus=0;
		  $model->save();
		}
		echo CJSON::encode(array(
                'status'=>'success',
                'div'=>'Data deleted'
				));
        Yii::app()->end();
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDeletedetail()
	{
		$id=$_POST['id'];
		foreach($id as $ids)
		{
		  $model=Journaldetail::model()->findbyPK($ids);
		  $model->delete();
		}
		echo CJSON::encode(array(
                'status'=>'success',
                'div'=>'Data deleted'
				));
        Yii::app()->end();
	}

	public function actionApprove()
	{
	  parent::actionApprove();
      $id=$_POST['id'];
      foreach($id as $ids)
      {
        //$model=$this->loadModel($ids);
        $a = Yii::app()->user->name;
        $connection=Yii::app()->db;
        $transaction=$connection->beginTransaction();
        try
        {
          $sql = 'call ApproveJournal(:vid, :vlastupdateby)';
          $command=$connection->createCommand($sql);
          $command->bindValue(':vid',$ids,PDO::PARAM_INT);
          $command->bindValue(':vlastupdateby', $a,PDO::PARAM_STR);
          $command->execute();
          $transaction->commit();
          $this->GetSMessage('agjinsertsuccess');
        }
        catch(Exception $e) // an exception is raised if a query fails
        {
            $transaction->rollBack();
            $this->GetMessage($e->getMessage());
        }
      }
      Yii::app()->end();
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
	  parent::actionIndex();
	  $this->lookupdata();
		$model=new Genjournal('search');
		$model->unsetAttributes();  // clear any default values

protected/views/genjournal/_form.php
<div class="form">
<?php 
$journaldetail->genjournalid= $model->genjournalid;
$form=$this->beginWidget('CActiveForm', array(
	'id'=>'project-form',
	'enableAjaxValidation'=>false,
	'htmlOptions'=>array('enctype'=>'multipart/form-data')
)); ?>
<?php
$this->widget('ToolbarButton',array(
	'isSave'=>true,'UrlSave'=>'genjournal/write',
	'isCancel'=>true,'UrlCancel'=>'genjournal/cancelwrite'
));
?>
<?php echo $form->hiddenField($model,'genjournalid'); ?>
	<table>
	  <tr>
		<td>
		  <div class="row">
		<?php echo $form->labelEx($model,'journaldate'); ?>
		<?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
              'attribute'=>'journaldate',
              'model'=>$model,
              // additional javascript options for the date picker plugin
              'options'=>array(
                  'showAnim'=>'fold',
				  'dateFormat'=>Yii::app()->params['dateviewcjui'],
				  'changeYear'=>true,
				  'changeMonth'=>true,
                                  'yearRange'=>'1900:+0'
              ),
              'htmlOptions'=>array(
                  'style'=>'height:20px',
                  'size'=>'20',
              ),
          ));?>
		<?php echo $form->error($model,'journaldate'); ?>
	</div>
		</td>
		<td>
		  		  <div class="row">
		<?php echo $form->labelEx($model,'postdate'); ?>
		<?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
              'attribute'=>'postdate',
              'model'=>$model,
              // additional javascript options for the date picker plugin
              'options'=>array(
                  'showAnim'=>'fold',
				  'dateFormat'=>Yii::app()->params['dateviewcjui'],
				  'changeYear'=>true,
				  'changeMonth'=>true,
                                  'yearRange'=>'1900:+0'
              ),
              'htmlOptions'=>array(
                  'style'=>'height:20px',
                  'size'=>'20',
              ),
          ));?>
		<?php echo $form->error($model,'postdate'); ?>
	</div>
		</td>
		<td>
		  <div class="row">
		<?php echo $form->labelEx($model,'referenceno'); ?>
		<?php echo $form->textfield($model,'referenceno',array('size'=>50, 'max'=>50)); ?>
		<?php echo $form->error($model,'referenceno'); ?>
	</div>
		</td>
		<td>
		  <div class="row">
		<?php echo $form->labelEx($model,'journalnote'); ?>
		<?php echo $form->textArea($model,'journalnote',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'journalnote'); ?>
	</div>
		</td>
	</table>
<?php $this->endWidget(); ?>
	<?php
	$this->widget('zii.widgets.jui.CJuiTabs', array(
	'tabs' => array(
		'Journal Detail' => array('content' => $this->renderPartial('indexdetail',
			array('journaldetail'=>$journaldetail),true)),
	),
	// additional javascript options for the tabs plugin
	'options' => array(
		'collapsible' => true,
	),
));?>
</div><!-- form -->

protected/views/genjournal/_help.php
<?php echo Catalogsys::model()->getcatalog(genjournalhelp'); ?>

protected/views/genjournal/_helpdetail.php
<h1>Pendahuluan</h1>
Modul Absence Rule digunakan untuk mendaftarkan detail aturan main absensi dari daftar schedule.<br>
<br>

protected/views/genjournal/_helpdetailmodif.php
<h1>Keterangan Field</h1>

<table>
  <tr>
	<td>
	  <strong>Nama Field</strong>
	</td>
	<td>
	  <strong>Jenis Field</strong>
	</td>
	<td>
	  <strong>Keterangan</strong>
	</td>
  </tr>
  <tr>
	<td>
	  Account
	</td>
	<td>
	  Pilihan dari modul <a href="index.php?r=account/index">Account</a>
	</td>
	<td>
	  Nama Account
	</td>
  </tr>
  <tr>
	<td>
	  Debit
	</td>
	<td>
	  Angka, 0-9
	</td>
	<td>
	  Nilai Debit
	</td>
  </tr>
  <tr>
	<td>
	  Credit
	</td>
	<td>
	  Angka, 0-9
	</td>
	<td>
	  Nilai Kredit
	</td>
  </tr>
  <tr>
	<td>
	  Currency
	</td>
	<td>
	  Pilihan, dari modul <a href="index.php?r=currency/index">Currency</a>
	</td>
	<td>
	  Mata Uang yang digunakan dalam transaksi
	</td>
  </tr>
</table>


protected/views/genjournal/_helpmodif.php
<h1>Keterangan Field</h1>

<table>
  <tr>
	<td>
	  <strong>Nama Field</strong>
	</td>
	<td>
	  <strong>Jenis Field</strong>
	</td>
	<td>
	  <strong>Keterangan</strong>
	</td>
  </tr>
  <tr>
	<td>
	  Reference No
	</td>
	<td>
	  Karakter, A-Z, a-z, 0-9
	</td>
	<td>
	  No Referensi yang digunakan sebagai acuan ketika memasukkan data beginning stock
	</td>
  </tr>
  <tr>
	<td>
	  Journal Date
	</td>
	<td>
	  Format Tanggal, yyyy-mm-dd, hh:MM:ss
	</td>
	<td>
	  Tanggal Journal
	</td>
  </tr>
  <tr>
	<td>
	  Post Date
	</td>
	<td>
	  Format Tanggal, yyyy-mm-dd, hh:MM:ss
	</td>
	<td>
	  Tanggal Posting, mengacu kepada periode accounting.
	</td>
  </tr>
  <tr>
	<td>
	  Journal Note
	</td>
	<td>
	  Karakter, A-Z, a-z
	</td>
	<td>
	  Catatan / Keterangan Journal
	</td>
  </tr>
  <tr>
	<td>
	  Record Status
	</td>
	<td>
	  Check / uncheck
	</td>
	<td>
	  Status aktif / tidak aktif
	</td>
  </tr>
</table>


protected/views/genjournal/indexdetail.php
<?php
$this->breadcrumbs=array(
	'Genjournals',
);
$pageSize=Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']);
?>
<script type="text/javascript">
// here is the magic
function adddata1()
{
    <?php echo CHtml::ajax(array(
			'url'=>array('genjournal/createdetail'),
            'data'=> "js:$(this).serialize()",
            'type'=>'post',
            'dataType'=>'json',
            'success'=>"function(data)
            {
				document.getElementById('messages').innerHTML = '';
                if (data.status == 'success')
                {
                    $('#createdialog1 div.divcreate1').html(data.div);
					$('#Journaldetail_journaldetailid').val('');
					$('#Journaldetail_accountid').val('');
					$('#account_name').val('');
					$('#Journaldetail_debit').val('0');
					$('#Journaldetail_credit').val('0');
					$('#Journaldetail_currencyid').val('');
					$('#currencyname').val('');
					$('#Journaldetail_detailnote').val('');
					$('#Journaldetail_ratevalue').val('1');
                          // Here is the trick: on submit-> once again this function!
                    $('#createdialog1').dialog('open');
                }
                else
                {
                    document.getElementById('messages').innerHTML = data.div;
                }
            } ",
            ))?>;
    return false;
}
</script>
<script type="text/javascript">
function editdata1()
{
    <?php
	echo CHtml::ajax(array(
			'url'=>array('genjournal/updatedetail'),
            'data'=> array('id'=>'js:$.fn.yiiGridView.getSelection("detaildatagrid")'),
            'type'=>'post',
            'dataType'=>'json',
            'success'=>"function(data)
            {
document.getElementById('messages').innerHTML = '';
                if (data.status == 'success')
                {
                    $('#createdialog1 div.divcreate1').html(data.div);
					$('#Journaldetail_journaldetailid').val(data.journaldetailid);
					$('#Journaldetail_accountid').val(data.accountid);
					$('#account_name').val(data.accountname);
					$('#Journaldetail_debit').val(data.debit);
					$('#Journaldetail_credit').val(data.credit);
					$('#Journaldetail_currencyid').val(data.currencyid);
					$('#currencyname').val(data.currencyname);
					$('#Journaldetail_detailnote').val(data.detailnote);
					$('#Journaldetail_ratevalue').val(data.ratevalue);
                          // Here is the trick: on submit-> once again this function!
                    $('#createdialog1').dialog('open');
                }
                else
                {
                    document.getElementById('messages').innerHTML = data.div;
                }
            } ",
            ))?>;
    return false;
}
</script>
<script type="text/javascript">
function deletedata1()
{
    <?php
	echo CHtml::ajax(array(
			'url'=>array('genjournal/deletedetail'),
            'data'=> array('id'=>'js:$.fn.yiiGridView.getSelection("detaildatagrid")'),
            'type'=>'post',
            'dataType'=>'json',
            'success'=>"function(data)
            {

            } ",
            ))?>;
	$.fn.yiiGridView.update('detaildatagrid');
    return false;
}
</script>
<script type="text/javascript">
function refreshdata1()
{
    $.fn.yiiGridView.update('detaildatagrid');
    return false;
}
</script>
<?php $this->beginWidget('zii.widgets.jui.CJuiDialog', array( // the dialog
    'id'=>'createdialog1',
    'options'=>array(
        'title'=>'Form Dialog',
        'autoOpen'=>false,
        'modal'=>true,
        'width'=>'auto',
        'height'=>'auto',
    ),
));?>
<div id="divcreate1"></div>
<?php echo $this->renderPartial('_formdetail', array('model'=>$journaldetail)); ?>
<?php $this->endWidget();?>
<?php
$this->widget('ToolbarButton',
	array('isCreate'=>true,'UrlCreate'=>'adddata1()',
	'isRefresh'=>true,'UrlRefresh'=>'refreshdata1()',
	'UrlDownload'=>'downloaddata1()',
	'isEdit'=>true,'UrlEdit'=>'editdata1()',
	'isDelete'=>true,'UrlDelete'=>'deletedata1()',
	'isRecordPage'=>true,'PageSize'=>$pageSize,'OnChange'=>"$.fn.yiiGridView.update('detaildatagrid',{data:{pageSize: $(this).val() }})"));
?>
<?php
$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'detaildatagrid',
	'dataProvider'=>$journaldetail->search(),
  'selectableRows'=>1,
	'template'=>'{pager}<br>{items}{pager}',
	'columns'=>array(
    array(
      'class'=>'CCheckBoxColumn',
      'id'=>'ids',
    ),
	array('name'=>'journaldetailid', 'visible'=>false,'header'=>'ID','value'=>'$data->journaldetailid','htmlOptions'=>array('width'=>'1%')),
	array('name'=>'accountid', 'header'=>'Account Code','value'=>'$data->account->accountcode'),
	array('name'=>'accountid', 'header'=>'Account Name','value'=>'$data->account->accountname'),
            array(
      'name'=>'debit',
      'type'=>'raw',
                'value'=>'Yii::app()->numberFormatter->format(Yii::app()->params["defaultnumberprice"],$data->debit)',
     ),
            array(
      'name'=>'credit',
      'type'=>'raw',
                'value'=>'Yii::app()->numberFormatter->format(Yii::app()->params["defaultnumberprice"],$data->credit)',
     ),
	array('name'=>'currencyid', 'value'=>'$data->currency->currencyname'),
            array(
      'name'=>'ratevalue',
      'type'=>'raw',
                'value'=>'Yii::app()->numberFormatter->format(Yii::app()->params["defaultnumberprice"],$data->ratevalue)',
     ),
        'detailnote'
  ),
));
?>